import Head from 'next/head';
import Header from './Header';
import SubHeader from './SubHeader';
import { useState } from 'react';
import Backdrop from './Backdrop';

const Layout = ({ children }) => {

    const [ active, setActive ] = useState(false);

    const handleLoginModal = () => {
        setActive(!active)
    }

    return (
        <>
            <Head>
                    <title>Small Margins | Running Specialists</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" />
                    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700;900&family=Lato:wght@300;400&display=swap" rel="stylesheet" />
            </Head>
            <Header 
                active={active} 
                setActive={setActive} 
                handleLoginModal={handleLoginModal}
            />
            <SubHeader />
            <Backdrop active={active} setActive={setActive} />
            <div className="container">
                <main className="main">
                    {children}
                </main>
            </div>
        </>
    )
}

export default Layout;
