import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';
import ShoesList from '../components/ShoesList';

export default function Home({ shoes }) {
  return (
    <div className='app'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShoesList shoes={shoes} />
      <h1>Welcome to small-margins</h1>
    </div>
  )
}

export const getStaticProps = async(context) => {
  const res = await axios.get('http://localhost:1337/running-shoes');
  const shoes = res.data;

  return {
    props: {
      shoes
    }
  }
}
