import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';
import ShoesList from '../components/ShoesList';
import Header from '../components/Header';
import SubHeader from '../components/SubHeader';
import Hero from '../components/Hero';

export default function Home({ shoes }) {
  return (
    <div className='app'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;700;900&family=Lato:wght@300;400&display=swap" rel="stylesheet" />
      </Head>
      {/* <Header />
      <SubHeader /> */}
      <Hero />
      <ShoesList shoes={shoes} />
    </div>
  )
}

export const getStaticProps = async(context) => {
  const res = await axios.get('http://localhost:1337/running-shoes');
  const shoes = res.data;

  return {
    props: {
      shoes
    }
  }
}
